import { calcJobTotals, formatCurrency, formatHours } from './pricing';
import { JOB_TYPES } from '../data/jobTypes';
import { jsPDF } from 'jspdf';

// ---------------------------------------------------------------------------
// buildPDF — constructs a real jsPDF document from job data.
// No html2canvas. No screenshots. Pure vector layout → crisp on every device.
// ---------------------------------------------------------------------------
async function buildPDF(job, settings, mode, totals) {
  // ── Page setup ──────────────────────────────────────────────────────────
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'letter' });
  const PW = doc.internal.pageSize.getWidth();   // 612 pt
  const PH = doc.internal.pageSize.getHeight();  // 792 pt
  const ML = 40; const MR = 40; const MT = 36; const MB = 36;
  const CW = PW - ML - MR;  // content width

  // ── Brand colours ───────────────────────────────────────────────────────
  const GOLD   = [245, 158, 11];
  const BLACK  = [17,  17,  17];
  const GREY   = [85,  85,  85];
  const LTGREY = [230, 230, 230];
  const BGROW  = [250, 250, 250];
  const NOTEBG = [255, 251, 235];
  const NOTEBDR= [253, 230, 138];
  const DISCBDR= [229, 231, 235];

  // ── Helper: set fill colour ──────────────────────────────────────────────
  const setFill = (rgb) => doc.setFillColor(rgb[0], rgb[1], rgb[2]);
  const setDraw = (rgb) => doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
  const setFont = (size, style = 'normal', rgb = [0,0,0]) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    doc.setTextColor(rgb[0], rgb[1], rgb[2]);
  };

  // ── Pagination helper ────────────────────────────────────────────────────
  let y = MT;
  const BOTTOM_SAFE = PH - MB - 60; // leave room for footer

  function checkPage(needed = 20) {
    if (y + needed > BOTTOM_SAFE) {
      drawFooter();
      doc.addPage();
      y = MT;
    }
  }

  function drawFooter() {
    const fy = PH - MB;
    doc.setDrawColor(230, 230, 230);
    doc.setLineWidth(0.5);
    doc.line(ML, fy - 8, PW - MR, fy - 8);
    setFont(8, 'normal', [170, 170, 170]);
    const companyName = settings.companyName || 'Saybrook Electric, LLC.';
    doc.text(companyName, ML, fy);
    doc.text('Generated by SBK Estimator', PW - MR, fy, { align: 'right' });
    const pageCount = doc.internal.getNumberOfPages();
    doc.text(`Page ${pageCount}`, PW / 2, fy, { align: 'center' });
  }

  // ── Derived data ─────────────────────────────────────────────────────────
  const companyName  = settings.companyName || 'Saybrook Electric, LLC.';
  const date         = new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' });
  const isMultiScope = totals.isMultiScope;
  const allLineDetails = isMultiScope
    ? totals.scopeTotals.flatMap(s => s.lineDetails || [])
    : (totals.lineDetails || []);

  const jobType   = JOB_TYPES.find(t => t.id === job.jobType)?.label || job.jobType || 'Electrical Work';
  const scopeTitle = job.scopeTitle || (isMultiScope
    ? (job.scopes || []).map(s => JOB_TYPES.find(t => t.id === s.jobType)?.label || s.title).join(' + ')
    : jobType);

  const laborRate  = settings.laborRate || 95;
  const discount   = job.discount || 0;
  const discountAmt = totals.grandTotal * (discount / 100);
  const finalTotal  = totals.grandTotal - discountAmt;

  // ── LOGO ─────────────────────────────────────────────────────────────────
  if (settings.logoBase64) {
    try {
      const maxW = 110; const maxH = 50;
      // detect format from data URI
      const fmt = settings.logoBase64.startsWith('data:image/png') ? 'PNG' : 'JPEG';
      // Create an Image to get natural dimensions
      await new Promise((resolve) => {
        const img = new Image();
        img.onload = () => {
          const ratio = Math.min(maxW / img.width, maxH / img.height, 1);
          const w = img.width * ratio;
          const h = img.height * ratio;
          doc.addImage(settings.logoBase64, fmt, ML, y, w, h);
          resolve();
        };
        img.onerror = resolve;
        img.src = settings.logoBase64;
      });
    } catch(e) { /* skip logo on error */ }
  }

  // ── HEADER right side: ESTIMATE label + meta ─────────────────────────────
  const headerRight = ML + CW;
  setFont(28, 'bold', GOLD);
  doc.text('ESTIMATE', headerRight, y + 22, { align: 'right' });

  setFont(9, 'normal', GREY);
  doc.text(`Date: ${date}`, headerRight, y + 36, { align: 'right' });
  doc.text(`Job #: ${(job.id || '').slice(-6).toUpperCase()}`, headerRight, y + 48, { align: 'right' });
  setFont(9, 'bold', BLACK);
  doc.text(scopeTitle, headerRight, y + 62, { align: 'right' });

  // ── Company block (left) ─────────────────────────────────────────────────
  const logoBottom = settings.logoBase64 ? y + 54 : y;
  let cx = logoBottom + 4;
  setFont(14, 'bold', BLACK);
  doc.text(companyName, ML, cx);  cx += 14;
  setFont(9, 'normal', GREY);
  if (settings.companyAddress) { doc.text(settings.companyAddress, ML, cx); cx += 11; }
  if (settings.companyPhone)   { doc.text(settings.companyPhone,   ML, cx); cx += 11; }
  if (settings.companyEmail)   { doc.text(settings.companyEmail,   ML, cx); cx += 11; }
  if (settings.companyLicense) { doc.text(`License #${settings.companyLicense}`, ML, cx); cx += 11; }

  // ── Gold rule under header ────────────────────────────────────────────────
  y = Math.max(cx, y + 72) + 10;
  setFill(GOLD); setDraw(GOLD);
  doc.setLineWidth(3);
  doc.line(ML, y, PW - MR, y);
  y += 14;

  // ── CUSTOMER block ────────────────────────────────────────────────────────
  checkPage(60);
  const custX = ML; const custY = y;
  setFill([249,249,249]); setDraw(GOLD);
  doc.setLineWidth(3);
  // left accent bar
  doc.line(custX, custY, custX, custY + 52);
  doc.setLineWidth(0.5);

  setFont(7, 'bold', [153,153,153]);
  doc.text('PREPARED FOR', custX + 8, custY + 10);
  setFont(11, 'bold', BLACK);
  doc.text(job.customerName || '—', custX + 8, custY + 22);
  setFont(9, 'normal', GREY);
  let custLine = 34;
  if (job.jobAddress)     { doc.text(job.jobAddress,     custX + 8, custY + custLine); custLine += 11; }
  if (job.customerPhone)  { doc.text(job.customerPhone,  custX + 8, custY + custLine); custLine += 11; }
  if (job.customerEmail)  { doc.text(job.customerEmail,  custX + 8, custY + custLine); custLine += 11; }

  y = custY + Math.max(custLine, 52) + 14;

  // ── LINE ITEMS TABLE ──────────────────────────────────────────────────────
  function drawTableHeader(cols) {
    // cols: [{label, x, w, align}]
    setFill(BLACK);
    doc.rect(ML, y, CW, 16, 'F');
    setFont(7, 'bold', GOLD);
    cols.forEach(c => {
      doc.text(c.label.toUpperCase(), c.x + (c.align === 'right' ? c.w : 0), y + 11,
               { align: c.align || 'left' });
    });
    y += 16;
  }

  function drawTableRow(cols, values, rowIndex) {
    const rowH = 18;
    checkPage(rowH + 4);
    if (rowIndex % 2 === 0) {
      setFill(BGROW);
      doc.rect(ML, y, CW, rowH, 'F');
    }
    setDraw(LTGREY); doc.setLineWidth(0.3);
    doc.line(ML, y + rowH, ML + CW, y + rowH);
    setFont(9, 'normal', BLACK);
    cols.forEach((c, i) => {
      doc.text(String(values[i] ?? ''), c.x + (c.align === 'right' ? c.w : 0), y + 13,
               { align: c.align || 'left' });
    });
    y += rowH;
  }

  // Section label
  function sectionLabel(text) {
    checkPage(24);
    setFont(7, 'bold', [153,153,153]);
    doc.text(text.toUpperCase(), ML, y + 8);
    y += 14;
  }

  if (isMultiScope && mode === 'itemized') {
    // Multi-scope itemized
    for (const s of totals.scopeTotals) {
      const jt = JOB_TYPES.find(t => t.id === s.jobType);
      sectionLabel(`${jt?.icon || ''} ${s.title || jt?.label || 'Scope'}`);
      const cols = [
        { label: 'Description', x: ML + 4,       w: CW * 0.50, align: 'left'  },
        { label: 'Qty',         x: ML + CW * 0.54, w: 40,       align: 'left'  },
        { label: 'Unit',        x: ML + CW * 0.66, w: 50,       align: 'left'  },
        { label: 'Amount',      x: ML,             w: CW - 4,   align: 'right' },
      ];
      drawTableHeader(cols);
      const rows = (s.lineDetails || []).filter(li => (li.qty || 0) > 0);
      rows.forEach((li, i) => drawTableRow(cols, [li.name, li.qty, li.unit || 'each', formatCurrency(li.subtotal)], i));
      // scope subtotal
      checkPage(20);
      setFont(9, 'bold', GREY);
      doc.text('Scope subtotal', PW - MR - 120, y + 14);
      doc.text(formatCurrency(s.subtotal), PW - MR, y + 14, { align: 'right' });
      y += 22;
    }
  } else if (mode === 'itemized') {
    sectionLabel('Line Items');
    const cols = [
      { label: 'Description', x: ML + 4,        w: CW * 0.50, align: 'left'  },
      { label: 'Qty',         x: ML + CW * 0.54, w: 40,       align: 'left'  },
      { label: 'Unit',        x: ML + CW * 0.66, w: 50,       align: 'left'  },
      { label: 'Amount',      x: ML,             w: CW - 4,   align: 'right' },
    ];
    drawTableHeader(cols);
    const rows = allLineDetails.filter(li => (li.qty || 0) > 0);
    rows.forEach((li, i) => drawTableRow(cols, [li.name, li.qty, li.unit || 'each', formatCurrency(li.subtotal)], i));
  } else {
    // Summary: name + qty only
    sectionLabel(`Scope of Work — ${scopeTitle}`);
    const cols = [
      { label: 'Item', x: ML + 4,  w: CW * 0.75, align: 'left' },
      { label: 'Qty',  x: ML + 4,  w: CW - 8,    align: 'right' },
    ];
    drawTableHeader(cols);
    const rows = allLineDetails.filter(li => (li.qty || 0) > 0);
    rows.forEach((li, i) => drawTableRow(cols, [li.name, `${li.qty} ${li.unit || 'each'}`], i));
  }

  y += 10;

  // ── TOTALS ────────────────────────────────────────────────────────────────
  const totW = 220; const totX = PW - MR - totW;

  function totalsRow(label, value, bold = false, colour = null) {
    checkPage(18);
    setFont(9, bold ? 'bold' : 'normal', colour || (bold ? BLACK : GREY));
    doc.text(label, totX, y + 12);
    doc.text(value,  PW - MR, y + 12, { align: 'right' });
    setDraw(LTGREY); doc.setLineWidth(0.3);
    doc.line(totX, y + 16, PW - MR, y + 16);
    y += 17;
  }

  if (mode === 'itemized') {
    totalsRow('Material', formatCurrency(totals.totalMaterial));
    totalsRow(`Labor (${formatHours(totals.totalLaborHrs)} @ $${laborRate}/hr)`, formatCurrency(totals.totalLaborCost));
    if (totals.totalAllIn > 0) totalsRow('Other Items', formatCurrency(totals.totalAllIn));
    totalsRow('Subtotal', formatCurrency(totals.subtotal));
    totalsRow(`Overhead & Profit (${totals.markupPct}%)`, formatCurrency(totals.markupAmt));
  }
  if (discount > 0) {
    totalsRow('Before Discount', formatCurrency(totals.grandTotal));
    totalsRow(`Discount (${discount}%)`, `-${formatCurrency(discountAmt)}`, false, [229, 62, 62]);
  }

  // Grand total bar
  checkPage(28);
  setFill(BLACK);
  doc.rect(totX - 4, y, totW + 4 + (PW - MR - totX - totW + 4), 24, 'F');
  setFont(11, 'bold', GOLD);
  const grandLabel = discount > 0 ? 'TOTAL AFTER DISCOUNT' : 'TOTAL ESTIMATE';
  doc.text(grandLabel, totX, y + 16);
  doc.text(formatCurrency(finalTotal), PW - MR, y + 16, { align: 'right' });
  y += 34;

  // ── NOTES ─────────────────────────────────────────────────────────────────
  if (job.notes) {
    checkPage(40);
    setFill(NOTEBG); setDraw(NOTEBDR); doc.setLineWidth(0.5);
    // measure text height
    const noteLines = doc.splitTextToSize(`Notes: ${job.notes}`, CW - 20);
    const noteH = noteLines.length * 12 + 14;
    doc.roundedRect(ML, y, CW, noteH, 3, 3, 'FD');
    setFont(9, 'bold', [120, 53, 15]);
    doc.text('Notes:', ML + 8, y + 12);
    setFont(9, 'normal', [120, 53, 15]);
    doc.text(noteLines, ML + 8, y + 12, { maxWidth: CW - 16 });
    y += noteH + 10;
  }

  // ── DISCLOSURE ────────────────────────────────────────────────────────────
  if (settings.estimateDisclosure) {
    checkPage(50);
    setFill([255,255,255]); setDraw(DISCBDR); doc.setLineWidth(0.5);
    const discLines = doc.splitTextToSize(settings.estimateDisclosure, CW - 20);
    const discH = discLines.length * 11 + 18;
    doc.roundedRect(ML, y, CW, discH, 3, 3, 'FD');
    setFont(8, 'bold', [55, 65, 81]);
    doc.text('Disclosure:', ML + 8, y + 12);
    setFont(8, 'normal', [107, 114, 128]);
    doc.text(discLines, ML + 8, y + 22, { maxWidth: CW - 16 });
    y += discH + 14;
  }

  // ── SIGNATURE BLOCK ───────────────────────────────────────────────────────
  checkPage(80);
  setDraw(LTGREY); doc.setLineWidth(0.5);
  doc.line(ML, y, PW - MR, y);
  y += 14;

  if (job.signature) {
    setFont(8, 'normal', [136,136,136]);
    doc.text('Customer Approval Signature', ML, y);
    y += 6;
    try {
      await new Promise((resolve) => {
        const img = new Image();
        img.onload = () => {
          const maxW = 160; const maxH = 60;
          const ratio = Math.min(maxW / img.width, maxH / img.height, 1);
          doc.addImage(job.signature, 'PNG', ML, y, img.width * ratio, img.height * ratio);
          resolve();
        };
        img.onerror = resolve;
        img.src = job.signature;
      });
      y += 68;
    } catch(e) { y += 10; }
    if (job.signedAt) {
      setFont(8, 'normal', [85,85,85]);
      doc.text(`Signed: ${new Date(job.signedAt).toLocaleString()}`, ML, y);
      y += 14;
    }
  } else {
    setFont(9, 'normal', [136,136,136]);
    doc.text('Customer Signature: _______________________________', ML, y + 12);
    doc.text('Date: ___________', PW - MR, y + 12, { align: 'right' });
    y += 28;
  }

  // ── FOOTER on last page ───────────────────────────────────────────────────
  drawFooter();

  return doc;
}

// ---------------------------------------------------------------------------
// generateQuotePDF — entry point (called from QuoteTab)
// ---------------------------------------------------------------------------
export function generateQuotePDF(job, settings, mode = 'summary') {
  const totals = calcJobTotals(job, settings);

  const customerName = (job.customerName || 'Customer').replace(/[^a-zA-Z0-9 _-]/g, '').replace(/\s+/g, '-');
  const fileName = `Estimate-${customerName}.pdf`;

  const isIOS = /iPhone|iPad|iPod/.test(navigator.userAgent) ||
    (navigator.userAgent.includes('Mac') && 'ontouchend' in document);
  const isStandalone = window.navigator.standalone === true ||
    window.matchMedia('(display-mode: standalone)').matches;

  // ── Show overlay immediately for feedback ─────────────────────────────────
  let overlay = document.getElementById('sbk-pdf-overlay');
  if (overlay) overlay.remove();
  overlay = document.createElement('div');
  overlay.id = 'sbk-pdf-overlay';
  overlay.style.cssText = 'position:fixed;inset:0;z-index:9998;background:#111;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:20px;padding:32px;';

  if (isIOS || isStandalone) {
    // iOS: show overlay with Back + Save buttons
    overlay.innerHTML = `
      <div style="color:#f59e0b;font-size:48px;">📄</div>
      <p style="color:#fff;font-size:18px;font-weight:900;text-align:center;">Estimate Ready</p>
      <p style="color:#888;font-size:14px;text-align:center;">${job.customerName || 'Customer'}</p>`;
    document.body.appendChild(overlay);

    const toolbar = document.createElement('div');
    toolbar.style.cssText = 'position:fixed;bottom:0;left:0;right:0;z-index:9999;background:#111;padding:12px 16px;display:flex;gap:12px;box-shadow:0 -2px 12px rgba(0,0,0,0.5);';

    const backBtn = document.createElement('button');
    backBtn.textContent = '← Back';
    backBtn.style.cssText = 'flex:1;background:#333;color:#fff;font-weight:700;font-size:15px;border:none;border-radius:10px;padding:14px;cursor:pointer;';
    backBtn.onclick = () => { overlay.remove(); toolbar.remove(); };

    const saveBtn = document.createElement('button');
    saveBtn.textContent = '⬆ Save / Share PDF';
    saveBtn.style.cssText = 'flex:2;background:#f59e0b;color:#000;font-weight:900;font-size:15px;border:none;border-radius:10px;padding:14px;cursor:pointer;';

    saveBtn.onclick = async () => {
      saveBtn.textContent = 'Generating PDF…';
      saveBtn.disabled = true;
      try {
        const doc = await buildPDF(job, settings, mode, totals);
        const pdfBlob = doc.output('blob');
        const pdfFile = new File([pdfBlob], fileName, { type: 'application/pdf' });
        if (navigator.share && navigator.canShare && navigator.canShare({ files: [pdfFile] })) {
          await navigator.share({ files: [pdfFile] });
        } else {
          const url = URL.createObjectURL(pdfBlob);
          const a = document.createElement('a');
          a.href = url; a.download = fileName; a.click();
          setTimeout(() => URL.revokeObjectURL(url), 5000);
        }
      } catch (err) {
        console.error('PDF error:', err);
        alert('Could not generate PDF: ' + err.message);
      }
      saveBtn.textContent = '⬆ Save / Share PDF';
      saveBtn.disabled = false;
    };

    toolbar.appendChild(backBtn);
    toolbar.appendChild(saveBtn);
    document.body.appendChild(toolbar);

  } else {
    // Desktop: show spinner, generate, download, dismiss
    overlay.innerHTML = `
      <div style="color:#f59e0b;font-size:40px;">📄</div>
      <p style="color:#fff;font-size:17px;font-weight:700;">Generating PDF…</p>`;
    document.body.appendChild(overlay);

    (async () => {
      try {
        const doc = await buildPDF(job, settings, mode, totals);
        doc.save(fileName);
      } catch (err) {
        console.error('PDF error:', err);
        alert('Could not generate PDF: ' + err.message);
      }
      overlay.remove();
    })();
  }
}
